# Generated by Django 3.2.4 on 2021-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Los Barrios'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name_plural': 'Las Parroquias'},
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de barrio'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='numParques',
            field=models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Sexto')], verbose_name='Numero de parques'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de parroquia'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(choices=[('urbana', 'urbana'), ('rural', 'rural')], max_length=6, verbose_name='Tipo de parroquia'),
        ),
    ]
